### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Astahiell** [voxelhostpl/knowledge-base#3]
- [x] Jak wgrac pluginy/mody
- [x] Jak wgrac swoj swiat
- [ ] Mam lagi co robic
- [ ] Podlaczenie wlasnej domeny
- [ ] Bungeecord
- [ ] Datapacki
- [ ] AntyXray w silnik
- [ ] Pregeneracja
- [ ] Jak edytować pliki (configi)
- [ ] Dlaczego nie ma spigota
- [ ] Włączanie mapy z nowszej wersji na starszej wersji
- [ ] Jak ustawić resourcepack dla wszystkich graczy
- [ ] Co to harmonogram

**Comment by Astahiell** [comment]
* Jak wgrac pluginy/mody
* Jak wgrac swoj swiat/zmodyfikowac obecny 
Currently doing

**Comment by CDFN** [comment]
- [x] Jak wgrac pluginy/mody
- [x] Jak wgrac swoj swiat
- [ ] Mam lagi co robic
- [ ] Podlaczenie wlasnej domeny
- [ ] Bungeecord
- [ ] Datapacki

**Comment by Astahiell** [comment]
- [x] Jak wgrac pluginy/mody
- [x] Jak wgrac swoj swiat
- [ ] Mam lagi co robic
- [ ] Podlaczenie wlasnej domeny
- [ ] Bungeecord
- [ ] Datapacki
- [ ] AntyXray w silnik
- [ ]Pregeneracja
